apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
data:
  nginx.conf: |
    events {}
    http {
      server {
        listen 80;
        location / {
          proxy_set_header X-Duo-Header "Duo Auth Header";
          proxy_pass http://myduoservice;
        }
      }
    }