apiVersion: apps/v1
kind: Deployment
metadata:
  name: pingfederate
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pingfederate
  template:
    metadata:
      labels:
        app: pingfederate
    spec:
      containers:
        - name: pingfederate
          image: asherif0/pingfederate:2.1.0
          ports:
            - containerPort: 8080
          env:
            - name: HOST
              value: "http://localhost"
            - name: PORT
              value: "8080"
        - name: nginx
          image: nginx:latest
#          command: ["sudo mv /etc/nginx/conf.d/default.conf /etc/nginx/conf.d/default.conf.disabled"]
          ports:
            - containerPort: 8080
          volumeMounts:
            - name: nginx-conf
              mountPath: /etc/nginx/nginx.conf
              subPath: nginx.conf
      volumes:
        - name: nginx-conf
          configMap:
            name: nginx-config
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
data:
  nginx.conf: |
    user  nginx;
    worker_processes  auto;

    error_log  /var/log/nginx/error.log notice;
    pid        /var/run/nginx.pid;


    events {
      worker_connections  1024;
    }


    http {
      include       /etc/nginx/mime.types;
      default_type  application/octet-stream;

      log_format  main  '$remote_addr - $remote_user [$time_local] "$request" '
      '$status $body_bytes_sent "$http_referer" '
      '"$http_user_agent" "$http_x_forwarded_for"';

      access_log  /var/log/nginx/access.log  main;

      sendfile        on;
      #tcp_nopush     on;

      keepalive_timeout  65;

      #gzip  on;

      server {
        listen 8080;
        #server_name nginx-service.default.svc.cluster.local;
        location / {
          proxy_set_header X-Duo-Header "Duo Auth Header";
          proxy_pass http://thestreamingservice.site/;
        }
      }
    }
---
apiVersion: v1
kind: Service
metadata:
  name: pingfederate-service
spec:
  selector:
    app: pingfederate
  ports:
    - name: https
      port: 443
      targetPort: 443
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  selector:
    app: nginx
  ports:
    - name: nginx-port
      port: 8080
      targetPort: 8080