apiVersion: v1
kind: Service
metadata:
  name: pingfederate-service
spec:
  selector:
    app: pingfederate
  ports:
    - name: http
      port: 80
      targetPort: 80
    - name: https
        port: 443
        targetPort: 443
